service: alexa-ghosts
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:CreateTable"
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"
functions:
  hello:
    handler: handler.hello
    events:
      - alexaSkill
package:
  include:
    - node_modules/alexa-sdk/**
  exclude:
    - node_modules/**
